services:
  - type: web
    name: pdf-summerise-sih
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr libtesseract-dev
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
